### ISSUE TITLE
Fails to generate tests

### ISSUE THREAD

**Issue by shayanb** [audits-dev/truffle-test-generator#1]
While trying to run `npx ttg Contract" on a project, I get the following error:

```bash
node --version                                   
v12.16.2

npx ttg token
Please provide a contract name and be in the top-level directory of your Truffle project
 Error: ENOENT: no such file or directory, open '/build/contracts/token.json'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Object.<anonymous> (/node_modules/@audits/truffle-test-generator/testGen.js:97:28)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at .nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/libnpx/index.js:268:14 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/build/contracts/token.json'
}
```

**Comment by shayanb** [comment]
thanks I think that was the issue, the initial compile was failing due to some solc issues.
